Global("localization", nil)

Global("Locales", {
	["rus"] = { -- Russian, Win-1251
    ["CFG_AutoRestart"]="Автоперезапуск Рогов",
    ["Gold"] = "Золото",
    ["Coral"] = "Коралл",
    ["Granit"] = "Гранит",
    ["Tears"] = "Слезы",
    ["EpicT"] = "Рыжие",
    ["LegendT"] = "Чудесные",
    ["Embrium"] = "Эмбриум",
    ["EmbtoCoral"] = "Эмбриума до рога",
	["Spark"] = "Искры",
    ["Supplies"] = "Припасы",
    ["PayToMerc"] = "Плата наёмникам",
    ["Pay"] = "Плата",
    ["Search"] = "Поиск...",
    ["LabList"] = "Количество лабиринтов",
    
	["_Gold"] = "Золото",
	["_Coral"] = "Астральный коралл",
	["_Granit"] = "Астральный гранит",
	["_EpicTears"] = "Сияющая слеза дракона",
	["_LegendTears"] = "Пылающая слеза дракона",
	["_Embrium"] = "Эмбриум",
	["_Spark"] = "Искра героя",
    
    ["Harvest"] = "Время собирать урожай",
    ["Horn Not Found"] = "Вас ограбили или это новый Рог Изобилия?",
    ["Robbed"] = "Ограбили",
    ["New Horn"] = "Новый",
    ["Other"] = "другие",
    ["Full"] = "Готово",
	
	["Rows"] = "Количество строк",
	["TimeZone"] = "Сдвиг временной зоны",
	["Delay"] = "Время отсрочки рога",
	["Save"] = "Сохранить",
	["Shard"] = "Сервер",
	["Name"] = "Имя персонажа",
	["Type"] = "Ресурс",
	["Val"] = "Кол-во",
	["Days"] = "Дней",
	["Del"] = "Убрать",
	["Time"] = "Время",
	["Quality"] = "Печать",
	["EnsReady"] = "Порабощение откатилось",
	["h"] = "ч",
	["m"] = "м",
	["s"] = "с",
	["ready"] = "Готово",
	["Seal"] = "Заряд Печати",
	["General Options"] = "Основные настройки",
	["Announcement"] = "Уведомления",
	["FullMode"] = "Режим отображения всех рогов",
	["SuppliesLimit"] = "Лимит припасов для уведомления",
	["ShowInfo"] = "Показывать уведомления",
	["ShowHornReady"] = "Уведомления о созревших рогах",
	["ShowHornBuild"] = "Уведомления о постройке рога за коралл",
	["ShowHornForEmbrium"] = "Уведомления о постройке рога за эмбриум",
	["ShowEnsReady"] = "Откат Печати Порабощения",
	["ShowSupplies"] = "Уведомления о лимите припасов",
	["ShowDefenderUpdate"] = "Уведомления о поднятии ранга защитников",
	["From"]=" из ",
      
	["Bob Jackhammer"] = "Буба Молоток",
	["Bob the Muscle"] = "Боба Штангист",
	["None"] = "Нет",
	["Emerald"] = "Изумрудный",
	["Azure"] = "Лазурный",
	["Purple"] = "Пурпурный",
	["Amber"] = "Янтарный",
	["Forsaken"] = "Затерянный",
	["Relic"] = "Реликтовый",
	["Horn"] = "Рог изобилия",
	["Produce Gold"] = "Чеканить монеты",
	["Produce Coral"] = "Материализовать астральный коралл",
	["Produce Granit"] = "Материализовать астральный гранит",
	["Produce Embrium"] = "Производить Эмбриум",
	["Produce Epic Tears"] = "Производить сияющие слёзы",
	["Produce Legendary Tears"] = "Производить пылающие слёзы",
	["Manage Horn"] = "Управление рогом изобилия",
	["Horn Ready"] = "Рог изобилия готов к работе.",
	["Horn Busy"] = "Рог изобилия занят производством.",
	["Horn Completed"] = "Рог изобилия завершил производство",
	["Horn Broken"] = "Идёт процесс восстановления работоспособности",
	["Production Canceled"] = "Производство отменено.",
	["Ready for production"] = "Рог изобилия готов к новому производству!",
	["Spark Used"] = "Энергия Искр успешно преобразована!",
	["Can Build New"] = "Можно строить новый Рог Изобилия",
	["Can Build New For Embrium"] = "Можно строить новый Рог Изобилия за Эмбриум",
	["You need more supplies"] = "Надо больше припасов!",
	["Up defenders!"] = "Можно усилить защитников, поговори с Бобой Штангистом!",
	["Dungeon Keeper's Chest"] = "Сундучок хранителя подземелий",
	["WeeklyBoxSettings"] = "Какой ресурс получать из сундучка",
	["AutoUseWeaklyBoxes"] = "Автооткрытие сундучков ресурсов",
	["Layer"] = "Слой",
	["LayerFound"] = 6,
	["Private Allod"] = "Личный аллод",
	},
		
	["eng_eu"] = { -- English, Latin-1
    ["CFG_AutoRestart"]="Autorestart Horn",
    ["Gold"] = "Gold Ore",
    ["Coral"] = "Coral",
    ["Granit"] = "Granite",
	["EpicT"] = "EpicTear",
    ["LegendT"] = "LegendTear",
	["Embrium"] = "Embrium",
	["EmbtoCoral"] = "Embrium to next horn",
    ["Supplies"]="",
    ["Spark"] = "Sparks",
	["PayToMerc"]="Pay to Mercinaries",
    ["Pay"]="",
	["Search"]="Search...",
	["LabList"]="Number of labyrinths",
      
	  ["_Gold"] = "Gold Ore",	  
	  ["_Coral"] = "Astral Coral",
	  ["_Granit"] = "Astral Granite",
	  ["_Embrium"] = "Embrium",
	  ["_EpicTears"] = "Beaming dragon tear",
	  ["_LegendTears"] = "Glowing dragon tear",
	  ["_Spark"] = "Hero's Spark",

	  ["Harvest"] = "It's time to collect",
    ["Horn Not Found"] = "You were robbed or it's a new Horn of Abundance?",
    ["Robbed"]="Robbed",
    ["New Horn"]="New",    
    ["Other"]="other",
	
	["Rows"]="Numer of lines",
	["TimeZone"]="Timezone shift",
	["Delay"]="Horn delay time",
	["EnsReady"]="Enslavement is ready",
	["Seal"]="Seal",
	["From"]=" from ",
    
	["Bob Jackhammer"] = "Bob Jackhammer",
	["Horn"] = "Horn of Abundance",
	["Produce Gold"] = "Produce %d+ Gold",
	["Produce Coral"] = "Produce %d+ Astral Coral",
	["Produce Granit"] = "Produce %d+ Astral Granite",
	["Produce Embrium"] = "Produce %d+ Embrium",
	["Produce Epic Tears"] = "Produce %d+ Beaming",
	["Produce Legendary Tears"] = "Produce %d+ Glowing",
	["Manage Horn"] = "Horn of Abundance Menu",
	["Horn Ready"] = "Ready to operate.",
	["Horn Busy"] = "Production in progress.",
	["Horn Completed"] = "Construction completed.",
	["Horn Broken"] = "The Horn of Abundance has been harvested and now recovers.",
	["Production Canceled"] = "Production cancelled.",
	["Ready for production"] = "Horn of Abundance is ready for production!",
	["Spark Used"] = "Spark energy converted successfully!",
	["Can Build New"] = "You can build a new Horn of Abundance",
	["Can Build New For Embrium"] = "You can build a new Horn of Abundance for Embrium",
	["WeeklyBoxSettings"] = "What resource to get from the chest",
	["ShowDefenderUpdate"] = "Defender`s rank update annoucne",
	["LayerFound"] = 7,
	}
})

--We can now use an official method to get the client language
localization = common.GetLocalization()
function GTL( strTextName )
	return Locales[ localization ][ strTextName ] or Locales[ "eng_eu" ][ strTextName ] or strTextName
end
